CREATE DATABASE jav3Db
-----TAO BANG NGANH
IF OBJECT_ID('NGANH') IS NOT NULL
  DROP TABLE NGANH
GO
CREATE TABLE NGANH
(
ID  INT IDENTITY(1,1),
MaNganh NVARCHAR(10) NOT NULL,
TenNganh NVARCHAR(50) NULL,
CONSTRAINT PK_NGANH PRIMARY KEY(id)
)

------TAO BANG SINH VIEN
IF OBJECT_ID('SINHVIEN') IS NOT NULL
  DROP TABLE SINHVIEN
GO
CREATE TABLE SINHVIEN
(
ID INT IDENTITY(1,1),
MSV NVARCHAR(10) NOT NULL,
MaNganh nvarchar(10) not null,
Ten  NVARCHAR(20) NULL,
GioiTinh bit NULL,
DiaChi NVARCHAR(50) NULL,
Email NVARCHAR(50) NULL,
SDT   NVARCHAR(13) NULL,
Hinh NVARCHAR(100) null,
CONSTRAINT PK_SINHVIEN PRIMARY KEY(id),
CONSTRAINT FK_LOP_SINHVIEN FOREIGN KEY(id) REFERENCES Nganh
)
-- nhaan than
IF OBJECT_ID('NhanThan') IS NOT NULL
  DROP TABLE NhanThan
GO
CREATE TABLE NhanThan
(
ID INT IDENTITY(1,1) PrimaRy Key,
Ten nvarchar(20) not null,
Tuoi int not null,
SDT int not null,
DiaChi nvarchar(50) null, 
)
IF OBJECT_ID('Sinhvien_NhanThan') IS NOT NULL
  DROP TABLE Sinhvien_NhanThan
GO
CREATE TABLE Sinhvien_NhanThan
(
ID INT IDENTITY(1,1) PrimaRy Key,
Masv nvarchar(5) not null,
MaNhanThan nvarchar(5) not null,
CONSTRAINT FK_sinhvien FOREIGN KEY(id) REFERENCES Sinhvien,
CONSTRAINT FK_nhanThan FOREIGN KEY(id) REFERENCES NhanThan,
)